"""Barcha sahifalarda ishlatiladigan umumiy matnlar (nav, footer, tashkilot)."""

# Real, tasdiqlangan kontakt/tashkilot ma'lumoti — /api/content orqali tekshirilgan
# (https://promtchi.uz/api/content, 2026-09-15). Bu yerda o'zgarmas fallback sifatida
# saqlanadi — admin panelda kontaktlar o'zgarsa, shu faylni ham yangilash kerak.
ORG = {
    "name": "promtchi",
    "legal_name": "promtchi",
    "founded": "2023",
    "city_uz": "Toshkent",
    "city_ru": "Ташкент",
    "city_en": "Tashkent",
    "country_uz": "O'zbekiston",
    "country_ru": "Узбекистан",
    "country_en": "Uzbekistan",
    "telegram_handle": "@promtchiuz",
    "telegram_url": "https://t.me/promtchiuz",
    "instagram_url": "https://instagram.com/promtchiuz",
    "email": "hello@promtchi.uz",
    "phone": "+998 93 160 67 06",
    "phone_tel": "+998931606706",
    "logo": "https://promtchi.uz/static/logo.png",
}

LANG_NAMES = {"uz": "O'zbekcha", "ru": "Русский", "en": "English"}
LANG_SHORT = {"uz": "UZ", "ru": "RU", "en": "EN"}

# ── Asosiy navigatsiya (ichki sahifalarda) ────────────────────────────────
NAV = {
    "uz": {
        "home": "Bosh sahifa",
        "services": "Xizmatlar",
        "solutions": "Yechimlar",
        "portfolio": "Portfolio",
        "blog": "Blog",
        "faq": "FAQ",
        "about": "Biz haqimizda",
        "contact": "Aloqa",
        "cta": "Konsultatsiya olish",
        "home_url": "Bosh sahifaga",
    },
    "ru": {
        "home": "Главная",
        "services": "Услуги",
        "solutions": "Решения",
        "portfolio": "Портфолио",
        "blog": "Блог",
        "faq": "FAQ",
        "about": "О нас",
        "contact": "Контакты",
        "cta": "Получить консультацию",
        "home_url": "На главную",
    },
    "en": {
        "home": "Home",
        "services": "Services",
        "solutions": "Solutions",
        "portfolio": "Portfolio",
        "blog": "Blog",
        "faq": "FAQ",
        "about": "About",
        "contact": "Contact",
        "cta": "Get a consultation",
        "home_url": "Back to home",
    },
}

FOOTER = {
    "uz": {
        "tagline": "Keyingi loyiha sizniki bo'ladi.",
        "cta": "Bog'lanish",
        "rights": "Barcha huquqlar himoyalangan",
        "nav_title": "Sahifalar",
        "contact_title": "Aloqa",
        "privacy": "Maxfiylik siyosati",
        "terms": "Foydalanish shartlari",
    },
    "ru": {
        "tagline": "Следующий проект будет вашим.",
        "cta": "Связаться",
        "rights": "Все права защищены",
        "nav_title": "Страницы",
        "contact_title": "Контакты",
        "privacy": "Политика конфиденциальности",
        "terms": "Условия использования",
    },
    "en": {
        "tagline": "The next project will be yours.",
        "cta": "Get in touch",
        "rights": "All rights reserved",
        "nav_title": "Pages",
        "contact_title": "Contact",
        "privacy": "Privacy Policy",
        "terms": "Terms of Use",
    },
}

BREADCRUMB_HOME = {"uz": "Bosh sahifa", "ru": "Главная", "en": "Home"}

# ── Umumiy CTA/label matnlar (ichki sahifa shablonlari uchun) ─────────────
COMMON = {
    "uz": {
        "for_whom": "Kimlar uchun",
        "what_included": "Nimalarni o'z ichiga oladi",
        "problem_solution": "Muammo → Yechim",
        "features": "Funksiyalar",
        "tech": "Texnologiyalar",
        "process": "Ishlab chiqish jarayoni",
        "timeline_price": "Muddat va narx",
        "portfolio_examples": "Portfolio'dan misollar",
        "related_services": "Aloqador xizmatlar",
        "faq_title": "Savol — javob",
        "cta_title": "Loyihangizni muhokama qilamizmi?",
        "cta_sub": "G'oyangizni yozing — 24 soat ichida bog'lanamiz.",
        "cta_button": "Konsultatsiya olish",
        "read_more": "Batafsil",
        "view_case": "Loyihani ko'rish",
        "client": "Mijoz",
        "duration": "Muddat",
        "category": "Yo'nalish",
        "industry": "Sohasi",
        "goal": "Maqsad",
        "integrations": "Integratsiyalar",
        "result": "Natija",
        "problem": "Muammo",
        "solution": "Yechim",
        "all_services": "Barcha xizmatlar",
        "all_cases": "Barcha loyihalar",
        "all_solutions": "Barcha yechimlar",
        "not_found_title": "Sahifa topilmadi",
        "not_found_body": "Siz izlagan sahifa mavjud emas yoki ko'chirilgan.",
        "form_name": "Ism",
        "form_name_ph": "Ismingiz",
        "form_contact": "Telefon / Telegram",
        "form_contact_ph": "+998 __ ___ __ __ yoki @username",
        "form_type": "Loyiha turi",
        "form_message": "G'oyangiz",
        "form_message_ph": "Loyihangizni qisqacha yozing...",
        "form_submit": "Yuborish",
        "form_sending": "Yuborilmoqda...",
        "form_ok": "Rahmat! Tez orada bog'lanamiz ✓",
        "form_err_name": "Ismingizni kiriting",
        "form_err_contact": "Telefon raqamini (+998...) yoki Telegram @username'ni to'g'ri kiriting",
        "form_err_ratelimit": "Juda tez-tez — birozdan so'ng urining",
        "form_err_generic": "Xatolik — Telegram orqali yozing",
        "form_err_network": "Server bilan aloqa yo'q — Telegram orqali yozing",
        "form_consent_pre": "Yuborish orqali siz quyidagiga rozilik bildirasiz:",
        "form_consent_link": "Maxfiylik siyosati",
        "skip_to_content": "Asosiy kontentga o'tish",
        "main_nav_label": "Asosiy navigatsiya",
    },
    "ru": {
        "for_whom": "Кому подходит",
        "what_included": "Что входит",
        "problem_solution": "Проблема → Решение",
        "features": "Функции",
        "tech": "Технологии",
        "process": "Процесс разработки",
        "timeline_price": "Сроки и стоимость",
        "portfolio_examples": "Примеры из портфолио",
        "related_services": "Похожие услуги",
        "faq_title": "Вопрос — ответ",
        "cta_title": "Обсудим ваш проект?",
        "cta_sub": "Опишите идею — свяжемся с вами в течение 24 часов.",
        "cta_button": "Получить консультацию",
        "read_more": "Подробнее",
        "view_case": "Смотреть проект",
        "client": "Клиент",
        "duration": "Срок",
        "category": "Направление",
        "industry": "Отрасль",
        "goal": "Цель",
        "integrations": "Интеграции",
        "result": "Результат",
        "problem": "Проблема",
        "solution": "Решение",
        "all_services": "Все услуги",
        "all_cases": "Все проекты",
        "all_solutions": "Все решения",
        "not_found_title": "Страница не найдена",
        "not_found_body": "Запрошенная страница не существует или была перемещена.",
        "form_name": "Имя",
        "form_name_ph": "Ваше имя",
        "form_contact": "Телефон / Telegram",
        "form_contact_ph": "+998 __ ___ __ __ или @username",
        "form_type": "Тип проекта",
        "form_message": "Ваша идея",
        "form_message_ph": "Кратко опишите свой проект...",
        "form_submit": "Отправить",
        "form_sending": "Отправка...",
        "form_ok": "Спасибо! Скоро свяжемся ✓",
        "form_err_name": "Введите ваше имя",
        "form_err_contact": "Введите корректный номер телефона (+998...) или Telegram @username",
        "form_err_ratelimit": "Слишком часто — попробуйте чуть позже",
        "form_err_generic": "Ошибка — напишите нам в Telegram",
        "form_err_network": "Нет связи с сервером — напишите нам в Telegram",
        "form_consent_pre": "Отправляя форму, вы соглашаетесь с",
        "form_consent_link": "Политикой конфиденциальности",
        "skip_to_content": "Перейти к основному содержанию",
        "main_nav_label": "Основная навигация",
    },
    "en": {
        "for_whom": "Who it's for",
        "what_included": "What's included",
        "problem_solution": "Problem → Solution",
        "features": "Features",
        "tech": "Technologies",
        "process": "Development process",
        "timeline_price": "Timeline & pricing",
        "portfolio_examples": "Portfolio examples",
        "related_services": "Related services",
        "faq_title": "Question — answer",
        "cta_title": "Let's discuss your project?",
        "cta_sub": "Write down your idea — we'll get back to you within 24 hours.",
        "cta_button": "Get a consultation",
        "read_more": "Read more",
        "view_case": "View project",
        "client": "Client",
        "duration": "Duration",
        "category": "Category",
        "industry": "Industry",
        "goal": "Goal",
        "integrations": "Integrations",
        "result": "Result",
        "problem": "Problem",
        "solution": "Solution",
        "all_services": "All services",
        "all_cases": "All projects",
        "all_solutions": "All solutions",
        "not_found_title": "Page not found",
        "not_found_body": "The page you're looking for doesn't exist or was moved.",
        "form_name": "Name",
        "form_name_ph": "Your name",
        "form_contact": "Phone / Telegram",
        "form_contact_ph": "+998 __ ___ __ __ or @username",
        "form_type": "Project type",
        "form_message": "Your idea",
        "form_message_ph": "Briefly describe your project...",
        "form_submit": "Submit",
        "form_sending": "Sending...",
        "form_ok": "Thank you! We'll be in touch soon ✓",
        "form_err_name": "Please enter your name",
        "form_err_contact": "Please enter a valid phone number (+998...) or Telegram @username",
        "form_err_ratelimit": "Too many requests — please try again shortly",
        "form_err_generic": "Error — please message us on Telegram",
        "form_err_network": "No connection to server — please message us on Telegram",
        "form_consent_pre": "By submitting, you agree to our",
        "form_consent_link": "Privacy Policy",
        "skip_to_content": "Skip to main content",
        "main_nav_label": "Main navigation",
    },
}

# project_type <select> — qiymat (crm_constants.PROJECT_TYPE_SLUGS bilan mos) + til bo'yicha matn
PROJECT_TYPE_OPTIONS = {
    "uz": [
        ("web", "Web & ilova"), ("automation", "Avtomatlashtirish"),
        ("ai", "AI yechim"), ("crm_erp", "CRM / ERP"), ("other", "Boshqa"),
    ],
    "ru": [
        ("web", "Веб и приложение"), ("automation", "Автоматизация"),
        ("ai", "AI-решение"), ("crm_erp", "CRM / ERP"), ("other", "Другое"),
    ],
    "en": [
        ("web", "Web & App"), ("automation", "Automation"),
        ("ai", "AI Solution"), ("crm_erp", "CRM / ERP"), ("other", "Other"),
    ],
}

SITE_TITLE_SUFFIX = " — promtchi®"
