"""24 ta savol-javob — TZ 13-bo'lim ro'yxati, real ma'lumotlarga asoslangan
(hech qanday soxta va'da yo'q — narx/muddat sonlari saytdagi paketlar va
jarayon bo'limi bilan mos).

DIQQAT: bu fayl endi RUNTIME'da o'qilmaydi — faqat app/faq_store.py'ning
bir martalik seed_if_empty()'i uchun manba (`faq_items` jadvali bo'sh
bo'lsa shu yerdagi qiymatlar bilan to'ldiriladi). Saytdagi haqiqiy /faq/
kontenti va admin CRUD app/db.py FaqItem jadvalida (TZ 19-bo'lim) — shu
faylni tahrirlash saytga TA'SIR QILMAYDI, admin panel orqali o'zgartiring."""

FAQ = {
"uz": [
    ("Promtchi nima va qanday xizmatlar ko'rsatadi?",
     "promtchi — 2023-yildan Toshkentda faoliyat yuritayotgan raqamli mahsulotlar studiyasi. Veb-sayt va mobil ilova yaratish, biznes jarayonlarini avtomatlashtirish, AI yechimlar va CRM/ERP tizimlarini ishlab chiqamiz."),
    ("Promtchi qanday turdagi loyihalarni ishlab chiqadi?",
     "Landing page va korporativ saytlardan tortib, Telegram botlar, mobil ilovalar, AI chatbotlar va murakkab CRM/ERP tizimlarigacha — MVP'dan to'liq mahsulotgacha."),
    ("Promtchi kimlar uchun?",
     "Biznesini onlaynga chiqarayotgan tadbirkorlar, jarayonlarini raqamlashtirmoqchi bo'lgan kompaniyalar, startaplar va texnik hamkor izlayotgan jamoalar uchun."),
    ("Loyihani qanday boshlash mumkin?",
     "Saytdagi aloqa formasini to'ldiring yoki Telegram (@promtchiuz) orqali yozing — 24 soat ichida bog'lanamiz va bepul konsultatsiya o'tkazamiz."),
    ("Korporativ sayt yaratib berasizmi?",
     "Ha — landing page'dan ko'p sahifali korporativ saytgacha, admin panel bilan (kontentni o'zingiz boshqarasiz)."),
    ("Web ilova (Web App) yaratish mumkinmi?",
     "Ha — mijozlar kabineti, buyurtmalar paneli yoki ichki boshqaruv tizimi kabi web-app'larni ishlab chiqamiz."),
    ("Mobil ilova yaratib berasizmi?",
     "Ha — Flutter asosida Android va iOS uchun bitta kod bazasidan ilova yaratamiz, App Store/Google Play'ga joylashtiramiz."),
    ("Landing page qancha vaqtda tayyor bo'ladi?",
     "Odatda 7–14 kun ichida — loyihaning ishlaydigan birinchi versiyasi (MVP) 14 kunda tayyor bo'ladi."),
    ("Sayt yoki web app narxi qanday hisoblanadi?",
     "Loyiha hajmi va funksionallikka qarab. Texnik topshiriqdan so'ng 3 kun ichida aniq taklif tayyorlanadi. Boshlang'ich narxlar Narxlar bo'limida ko'rsatilgan."),
    ("AI chatbot yaratib berasizmi?",
     "Ha — savol-javob, buyurtma qabul qilish yoki qo'llab-quvvatlash uchun AI chatbot ishlab chiqamiz va saytga/Telegramга integratsiya qilamiz."),
    ("AI agent ishlab chiqish mumkinmi?",
     "Ha — vazifaga mos AI yechim (chatbot, ovozni matnga aylantirish, kontent generatsiya) loyihalaymiz; Notiq AI loyihamiz shunga misol."),
    ("AI chatbotni Telegram yoki saytga integratsiya qilasizmi?",
     "Ha — chatbot istalgan kanalga (sayt, Telegram, mobil ilova) integratsiya qilinadi."),
    ("AI yordamida biznes jarayonlarini avtomatlashtirish mumkinmi?",
     "Ha — AI'ni avtomatlashtirish zanjiriga (masalan, mijoz murojaatini tasniflash yoki kontent tayyorlash) qo'shib, jarayonni tezlashtiramiz."),
    ("Telegram bot yaratib berasizmi?",
     "Ha — oddiy avtojavob botdan tortib, CRM bilan ikki tomonlama sinxron ishlaydigan professional botgacha."),
    ("CRM tizimi yaratib berasizmi?",
     "Ha — Kanban voronka, Telegram sinxronizatsiya va statistikaga ega individual CRM tizimlarini quramiz."),
    ("ERP tizimi ishlab chiqasizmi?",
     "Ha — moliya, ombor, xodimlar va KPI modullarini birlashtiruvchi ERP tizimlarini ishlab chiqamiz."),
    ("Mavjud CRM yoki boshqa tizimlarga integratsiya qilasizmi?",
     "Ha — real loyihalarimizda AmoCRM, Bitrix24, UTEL va Meta Ads bilan real vaqtli integratsiyalarni qurganmiz."),
    ("Loyiha narxi qanday hisoblanadi?",
     "Loyiha hajmi, funksionallik va kerakli integratsiyalar soniga qarab. Aniq taklif texnik topshiriqdan so'ng 3 kun ichida beriladi."),
    ("Loyiha qancha vaqtda tayyor bo'ladi?",
     "Ishlaydigan birinchi versiya (MVP) — 14 kun, to'liq funksional va sinovdan o'tgan loyiha — 25 kun ichida (loyiha hajmiga qarab o'zgarishi mumkin)."),
    ("To'lov qanday amalga oshiriladi?",
     "Texnik topshiriqdan so'ng 3 kun ichida taklif tayyorlanadi. Tasdiqlangach, 30% oldindan, qolgan qismi loyiha yakunlanganda to'lanadi."),
    ("Qo'shimcha xarajatlar bo'lishi mumkinmi?",
     "Kelishilgan ish doirasidan tashqari qo'shimcha talab (scope o'zgarishi) alohida muhokama va kelishuvdan so'ng qo'shiladi. Domen/hosting kabi uchinchi tomon xizmatlari alohida hisoblanadi — bularning barchasi oldindan aniq aytiladi, yashirin to'lov yo'q."),
    ("Kod va loyiha huquqi kimga tegishli bo'ladi?",
     "Loyiha kodidan foydalanish huquqlari tomonlar o'rtasidagi shartnomada belgilanadi — odatda mijoz o'z loyihasidan foydalanish huquqiga ega bo'ladi, uchinchi tomon kutubxona va servislar esa o'zlarining litsenziya shartlariga bo'ysunadi."),
    ("Loyiha tugagandan keyin support bormi?",
     "Ha — tanlangan paketga qarab 14, 30 yoki 90 kunlik bepul texnik yordam beriladi. Bu muddatdan keyin ham qo'llab-quvvatlashni alohida kelishuv asosida davom ettirish mumkin."),
    ("Texnik xizmat ko'rsatish va yangilash mumkinmi?",
     "Ha — bepul yordam muddati tugagach ham, texnik xizmat va yangilanishlarni alohida kelishilgan shartlarda davom ettiramiz."),
],
"ru": [
    ("Что такое Promtchi и какие услуги вы предоставляете?",
     "promtchi — студия цифровых продуктов, работающая в Ташкенте с 2023 года. Разрабатываем веб-сайты и мобильные приложения, автоматизируем бизнес-процессы, создаём AI-решения и CRM/ERP системы."),
    ("Какие типы проектов разрабатывает Promtchi?",
     "От лендингов и корпоративных сайтов до Telegram-ботов, мобильных приложений, AI-чат-ботов и сложных CRM/ERP систем — от MVP до готового продукта."),
    ("Для кого Promtchi?",
     "Для предпринимателей, выводящих бизнес в онлайн, компаний, которые хотят оцифровать процессы, стартапов и команд в поиске технического партнёра."),
    ("Как начать проект?",
     "Заполните форму на сайте или напишите в Telegram (@promtchiuz) — свяжемся в течение 24 часов и проведём бесплатную консультацию."),
    ("Вы делаете корпоративные сайты?",
     "Да — от лендинга до многостраничного корпоративного сайта, с админ-панелью (вы сами управляете контентом)."),
    ("Можно ли заказать веб-приложение (Web App)?",
     "Да — разрабатываем веб-приложения: личный кабинет клиента, панель заказов или внутреннюю систему управления."),
    ("Вы разрабатываете мобильные приложения?",
     "Да — на Flutter для Android и iOS из единой кодовой базы, с публикацией в App Store/Google Play."),
    ("Сколько времени занимает лендинг?",
     "Обычно 7–14 дней — рабочая первая версия проекта (MVP) готова за 14 дней."),
    ("Как рассчитывается стоимость сайта или веб-приложения?",
     "В зависимости от объёма проекта и функциональности. Точное предложение готовится в течение 3 дней после технического задания. Стартовые цены указаны в разделе «Цены»."),
    ("Вы разрабатываете AI-чат-боты?",
     "Да — создаём AI-чат-боты для вопросов-ответов, приёма заказов или поддержки клиентов и интегрируем их в сайт/Telegram."),
    ("Можно ли разработать AI-агента?",
     "Да — проектируем AI-решение под конкретную задачу (чат-бот, распознавание речи, генерация контента); пример — наш проект Notiq AI."),
    ("Вы интегрируете AI-чат-бот с Telegram или сайтом?",
     "Да — чат-бот интегрируется в любой канал (сайт, Telegram, мобильное приложение)."),
    ("Можно ли автоматизировать бизнес-процессы с помощью AI?",
     "Да — добавляем AI в цепочку автоматизации (например, классификацию обращений клиентов или подготовку контента), ускоряя процесс."),
    ("Вы разрабатываете Telegram-ботов?",
     "Да — от простого бота с автоответами до профессионального бота с двусторонней синхронизацией с CRM."),
    ("Вы разрабатываете CRM-системы?",
     "Да — строим индивидуальные CRM-системы с Kanban-воронкой, синхронизацией с Telegram и статистикой."),
    ("Вы разрабатываете ERP-системы?",
     "Да — создаём ERP-системы, объединяющие модули финансов, склада, персонала и KPI."),
    ("Вы делаете интеграции с существующей CRM или другими системами?",
     "Да — в реальных проектах мы строили интеграции в реальном времени с AmoCRM, Bitrix24, UTEL и Meta Ads."),
    ("Как рассчитывается стоимость проекта?",
     "В зависимости от объёма проекта, функциональности и количества необходимых интеграций. Точное предложение даётся в течение 3 дней после технического задания."),
    ("Сколько времени занимает проект?",
     "Рабочая первая версия (MVP) — 14 дней, полностью функциональный и протестированный проект — 25 дней (сроки могут меняться в зависимости от объёма)."),
    ("Как происходит оплата?",
     "После технического задания предложение готовится в течение 3 дней. После согласования — 30% предоплата, остальное по завершении проекта."),
    ("Могут ли быть дополнительные расходы?",
     "Дополнительные требования вне согласованного объёма работ (изменение scope) добавляются только после отдельного обсуждения и согласования. Сторонние услуги — домен/хостинг — оплачиваются отдельно; всё это озвучивается заранее, скрытых платежей нет."),
    ("Кому принадлежат права на код и проект?",
     "Права на использование кода проекта определяются договором между сторонами — как правило, клиент получает право использовать свой проект, а сторонние библиотеки и сервисы подчиняются собственным условиям лицензирования."),
    ("Есть ли поддержка после завершения проекта?",
     "Да — в зависимости от выбранного пакета предоставляется 14, 30 или 90 дней бесплатной технической поддержки. После этого срока поддержку можно продолжить по отдельной договорённости."),
    ("Возможно ли техническое обслуживание и обновления?",
     "Да — даже после окончания бесплатного периода поддержки мы продолжаем техническое обслуживание и обновления на отдельно согласованных условиях."),
],
"en": [
    ("What is Promtchi and what services do you offer?",
     "promtchi is a digital product studio operating in Tashkent since 2023. We build websites and mobile apps, automate business processes, and develop AI solutions and CRM/ERP systems."),
    ("What kinds of projects does Promtchi build?",
     "Everything from landing pages and corporate websites to Telegram bots, mobile apps, AI chatbots and complex CRM/ERP systems — from MVP to a finished product."),
    ("Who is Promtchi for?",
     "For entrepreneurs bringing their business online, companies looking to digitize their processes, startups, and teams looking for a technical partner."),
    ("How do I start a project?",
     "Fill out the contact form on the site or message us on Telegram (@promtchiuz) — we'll respond within 24 hours and offer a free consultation."),
    ("Do you build corporate websites?",
     "Yes — from a landing page to a multi-page corporate website, with an admin panel so you manage the content yourself."),
    ("Can you build a web app?",
     "Yes — we build web apps such as a client dashboard, an order management panel, or an internal management system."),
    ("Do you build mobile apps?",
     "Yes — using Flutter for Android and iOS from a single codebase, published to the App Store/Google Play."),
    ("How long does a landing page take?",
     "Usually 7–14 days — a working first version of the project (MVP) is ready within 14 days."),
    ("How is website or web app pricing calculated?",
     "Based on project scope and functionality. An exact proposal is prepared within 3 days after the technical spec. Starting prices are listed in the Pricing section."),
    ("Do you build AI chatbots?",
     "Yes — we build AI chatbots for Q&A, order intake, or customer support, and integrate them into your website/Telegram."),
    ("Can you develop an AI agent?",
     "Yes — we design an AI solution tailored to the task (chatbot, speech-to-text, content generation); our Notiq AI project is one example."),
    ("Do you integrate AI chatbots with Telegram or a website?",
     "Yes — the chatbot can be integrated into any channel (website, Telegram, mobile app)."),
    ("Can business processes be automated with AI?",
     "Yes — we add AI into the automation chain (e.g. classifying customer inquiries or preparing content) to speed things up."),
    ("Do you build Telegram bots?",
     "Yes — from a simple auto-reply bot to a professional bot with two-way CRM synchronization."),
    ("Do you build CRM systems?",
     "Yes — we build custom CRM systems with a Kanban pipeline, Telegram sync and analytics."),
    ("Do you build ERP systems?",
     "Yes — we develop ERP systems that combine finance, inventory, staff and KPI modules."),
    ("Can you integrate with an existing CRM or other systems?",
     "Yes — on real projects we've built real-time integrations with AmoCRM, Bitrix24, UTEL and Meta Ads."),
    ("How is project pricing calculated?",
     "Based on project scope, functionality, and the number of integrations required. An exact proposal is given within 3 days after the technical spec."),
    ("How long does a project take?",
     "A working first version (MVP) — 14 days; a fully functional, tested project — 25 days (timelines can vary depending on scope)."),
    ("How does payment work?",
     "After the technical spec, a proposal is ready within 3 days. Once approved — 30% upfront, the rest on project completion."),
    ("Could there be additional costs?",
     "Additional requirements outside the agreed scope of work are only added after a separate discussion and agreement. Third-party services such as domain/hosting are billed separately — all of this is stated upfront, with no hidden fees."),
    ("Who owns the code and the project?",
     "Usage rights to the project's code are defined in the contract between the parties — the client typically receives the right to use their project, while third-party libraries and services remain subject to their own license terms."),
    ("Is there support after the project is finished?",
     "Yes — depending on the chosen package, you get 14, 30 or 90 days of free technical support. After that period, support can continue under a separate agreement."),
    ("Is ongoing maintenance and updates available?",
     "Yes — even after the free support period ends, we continue maintenance and updates under separately agreed terms."),
],
}
