"""Maxfiylik siyosati va Foydalanish shartlari — 3 tilli (TZ v2.0, 14-bo'lim).

Kod/IP huquqlari va boshqa qat'iy da'volar shartnomaga bog'langan holda,
umumiy va professional shaklda yozilgan (TZ 2-bo'lim, "Kod huquqi..." eslatmasi).
"""

LEGAL_SLUGS = {
    "privacy": {"uz": "maxfiylik-siyosati", "ru": "politika-konfidentsialnosti", "en": "privacy-policy"},
    "terms": {"uz": "foydalanish-shartlari", "ru": "usloviya-ispolzovaniya", "en": "terms-of-use"},
}

LEGAL_LABEL = {
    "uz": "Yuridik ma'lumot",
    "ru": "Юридическая информация",
    "en": "Legal",
}

UPDATED_LABEL = {
    "uz": "Oxirgi yangilanish",
    "ru": "Последнее обновление",
    "en": "Last updated",
}

UPDATED_DATE = "2026-09-15"

PRIVACY = {
    "uz": {
        "title": "Maxfiylik siyosati — promtchi®",
        "meta": "promtchi.uz saytida foydalanuvchi ma'lumotlari qanday yig'ilishi, ishlatilishi va himoyalanishi haqida maxfiylik siyosati.",
        "h1": "Maxfiylik siyosati",
        "intro": "Ushbu sahifada promtchi.uz saytidan foydalanganingizda qanday ma'lumot yig'ilishi, u nima uchun ishlatilishi va qanday himoyalanishi tushuntiriladi. Saytdan foydalanish orqali siz ushbu siyosat shartlariga rozilik bildirasiz.",
        "sections": [
            ("1. Qanday ma'lumot yig'amiz",
             "Aloqa formasi yoki Telegram bot orqali murojaat qoldirganda: ismingiz, telefon raqami yoki Telegram foydalanuvchi nomi, loyiha turi va xabar matni. Saytga tashrif buyurganda esa texnik ma'lumot (sahifa manzili, qurilma/brauzer turi, taxminiy joylashuv mamlakat darajasida) analitika xizmatlari orqali avtomatik yig'ilishi mumkin."),
            ("2. Ma'lumotdan qanday maqsadda foydalanamiz",
             "Yig'ilgan ma'lumot faqat sizning murojaatingizga javob berish, loyiha bo'yicha taklif tayyorlash va aloqada bo'lish uchun ishlatiladi. Analitika ma'lumotlari saytning qaysi bo'limlari foydali ekanini tushunish va uni yaxshilash uchun umumlashtirilgan holda ishlatiladi."),
            ("3. Kimlar bilan bo'lishamiz",
             "Sizning shaxsiy ma'lumotlaringiz uchinchi tomonlarga sotilmaydi yoki marketing maqsadida ijaraga berilmaydi. Ma'lumot faqat quyidagi hollarda uchinchi tomonga uzatilishi mumkin: xizmat ko'rsatish uchun ishlatiladigan texnik provayderlar (masalan, xosting, Telegram, email yuborish xizmati) va qonun talab qilgan hollarda."),
            ("4. Cookie va analitika",
             "Sayt ishlashi va foydalanuvchi tajribasini o'lchash uchun cookie fayllar hamda Google Analytics kabi analitika vositalaridan foydalanishi mumkin. Brauzeringiz sozlamalaridan cookie'larni cheklashingiz yoki o'chirishingiz mumkin — bu holda ba'zi funksiyalar to'liq ishlamasligi mumkin."),
            ("5. Ma'lumotni saqlash muddati",
             "Murojaat ma'lumotlari loyiha bo'yicha aloqa davom etgan va qonuniy hisobot/arxiv talablari uchun zarur bo'lgan muddat davomida saqlanadi, so'ngra o'chiriladi yoki anonimlashtiriladi."),
            ("6. Sizning huquqlaringiz",
             "Siz o'zingiz haqingizdagi ma'lumotni ko'rish, tuzatish yoki o'chirishni so'rash huquqiga egasiz. Buning uchun quyidagi aloqa manzillaridan biriga murojaat qiling."),
            ("7. Mijoz logotipi va fikr-mulohazalari",
             "Portfolio yoki saytda mijoz nomi, logotipi yoxud fikr-mulohazasi (testimonial) faqat tegishli mijozning aniq yozma roziligi olingandan so'ng joylashtiriladi."),
            ("8. Bolalar maxfiyligi",
             "Sayt kattalar (biznes vakillari) uchun mo'ljallangan bo'lib, ongli ravishda 16 yoshdan kichik shaxslarning shaxsiy ma'lumotlarini yig'maydi."),
            ("9. Siyosatga o'zgartirishlar",
             "Ushbu siyosat vaqti-vaqti bilan yangilanishi mumkin. Muhim o'zgarishlar bo'lsa, sahifadagi \"oxirgi yangilanish\" sanasi yangilanadi."),
            ("10. Biz bilan bog'lanish",
             "Maxfiylik bo'yicha savollar yoki so'rovlar uchun — aloqa sahifasidagi Telegram, email yoki telefon orqali murojaat qiling."),
        ],
    },
    "ru": {
        "title": "Политика конфиденциальности — promtchi®",
        "meta": "Политика конфиденциальности promtchi.uz — как собираются, используются и защищаются данные пользователей.",
        "h1": "Политика конфиденциальности",
        "intro": "На этой странице объясняется, какие данные собираются при использовании сайта promtchi.uz, для чего они используются и как защищаются. Используя сайт, вы соглашаетесь с условиями данной политики.",
        "sections": [
            ("1. Какие данные мы собираем",
             "При обращении через форму или Telegram-бота: имя, телефон или Telegram-логин, тип проекта и текст сообщения. При посещении сайта автоматически может собираться техническая информация (адрес страницы, тип устройства/браузера, примерное местоположение на уровне страны) через сервисы аналитики."),
            ("2. Для чего используются данные",
             "Собранные данные используются только для ответа на ваше обращение, подготовки предложения по проекту и связи с вами. Данные аналитики используются в обобщённом виде для понимания полезности разделов сайта и его улучшения."),
            ("3. С кем мы делимся данными",
             "Ваши личные данные не продаются и не сдаются в аренду третьим лицам в маркетинговых целях. Данные могут передаваться третьим лицам только в следующих случаях: технические провайдеры, необходимые для работы сервиса (хостинг, Telegram, сервис email-рассылки), и по требованию закона."),
            ("4. Cookie и аналитика",
             "Сайт может использовать cookie-файлы и инструменты аналитики (например, Google Analytics) для измерения работы сайта и опыта пользователей. Вы можете ограничить или отключить cookie в настройках браузера — часть функций при этом может работать неполностью."),
            ("5. Срок хранения данных",
             "Данные обращения хранятся в течение периода, необходимого для общения по проекту и для соблюдения требований отчётности/архива, после чего удаляются или обезличиваются."),
            ("6. Ваши права",
             "Вы имеете право запросить просмотр, исправление или удаление своих данных. Для этого обратитесь по одному из контактов ниже."),
            ("7. Логотип и отзывы клиентов",
             "Название, логотип или отзыв (testimonial) клиента публикуются в портфолио или на сайте только после получения явного письменного согласия соответствующего клиента."),
            ("8. Конфиденциальность детей",
             "Сайт предназначен для представителей бизнеса и сознательно не собирает персональные данные лиц младше 16 лет."),
            ("9. Изменения политики",
             "Данная политика может периодически обновляться. При существенных изменениях дата \"последнее обновление\" на странице будет обновлена."),
            ("10. Связь с нами",
             "По вопросам конфиденциальности обращайтесь через Telegram, email или телефон, указанные на странице контактов."),
        ],
    },
    "en": {
        "title": "Privacy Policy — promtchi®",
        "meta": "promtchi.uz privacy policy — how user data is collected, used and protected.",
        "h1": "Privacy Policy",
        "intro": "This page explains what data is collected when you use promtchi.uz, why it is used, and how it is protected. By using the site, you agree to the terms of this policy.",
        "sections": [
            ("1. What data we collect",
             "When you submit the contact form or message our Telegram bot: your name, phone number or Telegram username, project type, and message text. When you visit the site, technical information (page URL, device/browser type, approximate country-level location) may be collected automatically through analytics services."),
            ("2. How we use the data",
             "Collected data is used only to respond to your inquiry, prepare a project proposal, and stay in touch with you. Analytics data is used in aggregated form to understand which sections of the site are useful and to improve it."),
            ("3. Who we share data with",
             "Your personal data is not sold or rented to third parties for marketing purposes. Data may be shared with third parties only in the following cases: technical providers required to operate the service (hosting, Telegram, email delivery), and where required by law."),
            ("4. Cookies and analytics",
             "The site may use cookies and analytics tools (such as Google Analytics) to measure site performance and user experience. You can restrict or disable cookies in your browser settings — some functionality may then work incompletely."),
            ("5. Data retention",
             "Inquiry data is kept for as long as needed to communicate about the project and to meet reporting/archival requirements, after which it is deleted or anonymized."),
            ("6. Your rights",
             "You have the right to request access to, correction of, or deletion of your data. Contact us through one of the channels below to do so."),
            ("7. Client logos and testimonials",
             "A client's name, logo or testimonial is published in the portfolio or on the site only after that client's explicit written consent has been obtained."),
            ("8. Children's privacy",
             "The site is intended for business representatives and does not knowingly collect personal data from individuals under 16."),
            ("9. Changes to this policy",
             "This policy may be updated from time to time. If significant changes are made, the \"last updated\" date on this page will be revised."),
            ("10. Contact us",
             "For privacy-related questions or requests, reach us via the Telegram, email or phone listed on the contact page."),
        ],
    },
}

TERMS = {
    "uz": {
        "title": "Foydalanish shartlari — promtchi®",
        "meta": "promtchi.uz saytidan foydalanish shartlari va tomonlar o'rtasidagi umumiy qoidalar.",
        "h1": "Foydalanish shartlari",
        "intro": "Ushbu shartlar promtchi.uz saytidan foydalanish tartibini belgilaydi. Saytdan foydalanish orqali siz quyidagi shartlarga rozilik bildirasiz. Aniq loyiha bo'yicha xizmat ko'rsatish shartlari (narx, muddat, to'lov, javobgarlik) har bir mijoz bilan alohida tuziladigan shartnomada belgilanadi — ushbu sahifa faqat saytdan umumiy foydalanish qoidalarini o'z ichiga oladi.",
        "sections": [
            ("1. Sayt haqida",
             "promtchi.uz — Toshkentda faoliyat yurituvchi IT/raqamli mahsulotlar studiyasi promtchi'ning rasmiy sayti bo'lib, xizmatlar, portfolio va aloqa ma'lumotlarini taqdim etadi."),
            ("2. Saytdan ruxsat etilgan foydalanish",
             "Saytdan faqat qonuniy maqsadlarda, uning ishlashiga zarar yetkazmagan holda foydalanishingiz mumkin. Saytga avtomatlashtirilgan skanerlash, zararli kod joylashtirish yoki xizmatlarni ortiqcha yuklab, ishlashiga xalaqit berish taqiqlanadi."),
            ("3. Kontent va intellektual mulk",
             "Saytdagi matn, dizayn, grafika va boshqa kontentga bo'lgan huquqlar promtchi'ga tegishli, agar boshqacha ko'rsatilmagan bo'lsa. Mijoz uchun ishlab chiqilgan loyihalarning kod va intellektual mulk huquqlari har bir loyiha uchun tuzilgan alohida shartnomada belgilanadi; odatda to'liq to'lov amalga oshirilgandan so'ng asosiy loyiha kodi mijozga topshiriladi, uchinchi tomon kutubxona/litsenziyalar esa o'z shartlariga bo'ysunadi."),
            ("4. Xizmatlar tavsifi",
             "Saytdagi xizmat tavsiflari, jarayon bosqichlari va muddat diapazonlari umumiy yo'naltiruvchi ma'lumot sifatida berilgan bo'lib, aniq shartlar (narx, aniq muddat, kafolat) har bir loyihaning hajmi va murakkabligiga qarab alohida muzokara qilinadi va shartnomada qayd etiladi."),
            ("5. Portfolio va natijalar",
             "Portfolio bo'limidagi loyihalar va ko'rsatilgan natijalar real bajarilgan ishlarga asoslanadi. Kelajakdagi har qanday loyiha uchun aynan shunday natija kafolatlanmaydi — natijalar loyihaning shartlari, bozor va boshqa omillarga bog'liq."),
            ("6. Javobgarlikni cheklash",
             "Sayt \"mavjud holicha\" taqdim etiladi. promtchi saytning uzluksiz yoki xatosiz ishlashini kafolatlamaydi. Tashqi havolalar orqali ochiladigan uchinchi tomon saytlari uchun promtchi javobgar emas."),
            ("7. Shaxsiy ma'lumotlar",
             "Saytdan foydalanish jarayonida yig'iladigan shaxsiy ma'lumotlar Maxfiylik siyosatiga muvofiq qayta ishlanadi."),
            ("8. Shartlarga o'zgartirish",
             "Ushbu shartlar vaqti-vaqti bilan yangilanishi mumkin. Yangilangan shartlar sahifada e'lon qilingan paytdan boshlab kuchga kiradi."),
            ("9. Amal qiluvchi qonunchilik",
             "Ushbu shartlar O'zbekiston Respublikasi qonunchiligiga muvofiq talqin qilinadi."),
            ("10. Aloqa",
             "Ushbu shartlar yuzasidan savollar bo'lsa — aloqa sahifasidagi Telegram, email yoki telefon orqali murojaat qiling."),
        ],
    },
    "ru": {
        "title": "Условия использования — promtchi®",
        "meta": "Условия использования сайта promtchi.uz и общие правила взаимодействия сторон.",
        "h1": "Условия использования",
        "intro": "Данные условия регулируют порядок использования сайта promtchi.uz. Используя сайт, вы соглашаетесь с указанными ниже условиями. Конкретные условия оказания услуг по проекту (цена, сроки, оплата, ответственность) определяются в отдельном договоре с каждым клиентом — эта страница описывает только общие правила пользования сайтом.",
        "sections": [
            ("1. О сайте",
             "promtchi.uz — официальный сайт IT/digital-студии promtchi, работающей в Ташкенте, на котором представлены услуги, портфолио и контактная информация."),
            ("2. Разрешённое использование сайта",
             "Вы можете использовать сайт только в законных целях, не нанося вреда его работе. Запрещается автоматизированное сканирование, размещение вредоносного кода или чрезмерная нагрузка на сервис, нарушающая его работу."),
            ("3. Контент и интеллектуальная собственность",
             "Права на текст, дизайн, графику и прочий контент сайта принадлежат promtchi, если не указано иное. Права на код и интеллектуальную собственность по проектам, разработанным для клиентов, определяются отдельным договором для каждого проекта; как правило, основной код проекта передаётся клиенту после полной оплаты, а сторонние библиотеки/лицензии регулируются собственными условиями."),
            ("4. Описание услуг",
             "Описания услуг, этапы процесса и диапазоны сроков на сайте носят ориентировочный характер; конкретные условия (цена, точные сроки, гарантия) согласовываются отдельно в зависимости от объёма и сложности проекта и фиксируются в договоре."),
            ("5. Портфолио и результаты",
             "Проекты и указанные результаты в разделе портфолио основаны на реально выполненных работах. Такой же результат для будущих проектов не гарантируется — результаты зависят от условий проекта, рынка и других факторов."),
            ("6. Ограничение ответственности",
             "Сайт предоставляется \"как есть\". promtchi не гарантирует бесперебойную или безошибочную работу сайта. promtchi не несёт ответственности за сторонние сайты, открываемые по внешним ссылкам."),
            ("7. Персональные данные",
             "Персональные данные, собираемые при использовании сайта, обрабатываются в соответствии с Политикой конфиденциальности."),
            ("8. Изменения условий",
             "Данные условия могут периодически обновляться. Обновлённые условия вступают в силу с момента публикации на странице."),
            ("9. Применимое право",
             "Данные условия толкуются в соответствии с законодательством Республики Узбекистан."),
            ("10. Контакты",
             "По вопросам, связанным с данными условиями, обращайтесь через Telegram, email или телефон, указанные на странице контактов."),
        ],
    },
    "en": {
        "title": "Terms of Use — promtchi®",
        "meta": "Terms of use for the promtchi.uz website and the general rules between the parties.",
        "h1": "Terms of Use",
        "intro": "These terms govern the use of the promtchi.uz website. By using the site, you agree to the terms below. Specific service terms for a project (price, timeline, payment, liability) are set out in a separate contract with each client — this page covers only the general rules of using the website.",
        "sections": [
            ("1. About the site",
             "promtchi.uz is the official website of promtchi, an IT/digital product studio based in Tashkent, presenting its services, portfolio and contact information."),
            ("2. Permitted use of the site",
             "You may use the site only for lawful purposes and must not harm its operation. Automated scraping, planting malicious code, or overloading the service in a way that disrupts its operation is prohibited."),
            ("3. Content and intellectual property",
             "Rights to the text, design, graphics and other content on the site belong to promtchi unless stated otherwise. Rights to the code and intellectual property of projects built for clients are defined in a separate contract for each project; typically the core project code is handed over to the client once payment is complete, while third-party libraries/licenses remain governed by their own terms."),
            ("4. Description of services",
             "Service descriptions, process stages and timeline ranges on the site are provided as general guidance; specific terms (price, exact timeline, guarantee) are negotiated separately depending on the scope and complexity of the project and recorded in the contract."),
            ("5. Portfolio and results",
             "Projects and results shown in the portfolio section are based on work actually delivered. The same results are not guaranteed for future projects — outcomes depend on the project's conditions, the market and other factors."),
            ("6. Limitation of liability",
             "The site is provided \"as is\". promtchi does not guarantee uninterrupted or error-free operation of the site. promtchi is not responsible for third-party sites reached via external links."),
            ("7. Personal data",
             "Personal data collected while using the site is processed in accordance with the Privacy Policy."),
            ("8. Changes to these terms",
             "These terms may be updated from time to time. Updated terms take effect once published on this page."),
            ("9. Governing law",
             "These terms are interpreted in accordance with the laws of the Republic of Uzbekistan."),
            ("10. Contact",
             "For questions about these terms, reach us via the Telegram, email or phone listed on the contact page."),
        ],
    },
}
