"""7 ta xizmat sahifasi — uz/ru/en. Har biri /​{lang}/xizmatlar/{slug}/ da chiqadi.

DIQQAT: bu fayl endi RUNTIME'da o'qilmaydi — faqat app/services_store.py'ning
bir martalik seed_if_empty()'i uchun manba (`services` jadvali bo'sh bo'lsa
shu yerdagi qiymatlar bilan to'ldiriladi). Saytdagi haqiqiy kontent va admin
CRUD app/db.py Service jadvalida (TZ 4/19-bo'lim) — shu faylni tahrirlash
saytga TA'SIR QILMAYDI, admin panel orqali o'zgartiring.

`key` — barcha tillarda bir xil (hreflang alternate va ichki bog'lanish uchun);
`slug` — har til uchun SEO-friendly URL bo'lagi (TZ 2-bo'lim).
"""

# tartib — sahifada va navigatsiyada shu ketma-ketlikda chiqadi
SERVICE_KEYS = ["web", "mobile", "crm", "erp", "ai", "telegram-bot", "automation"]

SLUGS = {
    "web": {"uz": "veb-sayt-yaratish", "ru": "razrabotka-saitov", "en": "web-development"},
    "mobile": {"uz": "mobil-ilova-yaratish", "ru": "razrabotka-mobilnyh-prilozhenij", "en": "mobile-app-development"},
    "crm": {"uz": "crm", "ru": "crm", "en": "crm"},
    "erp": {"uz": "erp", "ru": "erp", "en": "erp"},
    "ai": {"uz": "ai", "ru": "ai", "en": "ai"},
    "telegram-bot": {"uz": "telegram-bot", "ru": "telegram-bot", "en": "telegram-bot"},
    "automation": {"uz": "avtomatlashtirish", "ru": "avtomatizatsiya-biznesa", "en": "business-process-automation"},
}

SERVICES = {
"web": {
  "uz": dict(nav="Web & ilova", h1="Veb-sayt yaratish", title="Veb-sayt yaratish — korporativ sayt, landing, web-app | promtchi",
    meta="Toshkentda biznes uchun veb-sayt yaratish: landing page, korporativ sayt, onlayn do'kon va web-app. Tez, mobilga mos, SEO-tayyor. MVP — 14 kunda.",
    value="Biznesingiz uchun tez yuklanadigan, mobilga mos va qidiruv tizimlarida topiladigan veb-sayt yoki web-app quramiz — dizayndan serverga joylashgacha to'liq tsikl.",
    for_whom="Yangi biznesini onlaynga chiqarayotgan tadbirkorlar, korporativ saytga muhtoj kompaniyalar, onlayn do'kon yoki ichki web-app kerak bo'lgan jamoalar uchun.",
    problem="Ko'p bizneslar eskirgan, sekin yoki mobilga mos bo'lmagan saytga ega — bu mijozlarni yo'qotadi va Google'da past o'rinlarga tushiradi.",
    solution="Zamonaviy stack (server tomonda render qilinadigan, tez yuklanadigan sahifalar) bilan sayt quramiz — har bir sahifa SEO uchun tayyor, mobil-first va Core Web Vitals talablariga mos.",
    includes=["Landing page yoki ko'p sahifali korporativ sayt", "Onlayn do'kon (katalog, savat, to'lov integratsiyasi)", "Web-app (mijozlar kabineti, buyurtmalar paneli)", "Admin panel — kontentni o'zingiz boshqarasiz", "Domen, hosting va serverga joylashtirish", "SEO asoslari: metateglar, sitemap, tezlik optimizatsiyasi"],
    features=["Mobil-first, responsiv dizayn", "Tez yuklanish (optimallashtirilgan rasm/shrift/JS)", "Admin panel orqali kontentni o'zgartirish", "Aloqa formasi va Telegram/email bildirishnoma", "HTTPS, xavfsizlik sarlavhalari"],
    tech=["FastAPI / Django", "PostgreSQL", "JavaScript", "Server-side rendering"],
    price_note="Landing sahifa 300$ dan, ko'p sahifali korporativ sayt yoki web-app 800$ dan boshlanadi (Narxlar bo'limiga qarang). Aniq narx loyiha hajmiga bog'liq.",
    faq=[("Sayt qancha vaqtda tayyor bo'ladi?","Landing page odatda 7–14 kun, ko'p sahifali korporativ sayt yoki web-app 14–25 kun ichida tayyor bo'ladi."),
         ("Saytni o'zim tahrirlay olamanmi?","Ha — admin panel orqali matn, rasm va boshqa kontentni dasturchisiz o'zgartirasiz.")]),
  "ru": dict(nav="Веб и приложение", h1="Разработка сайтов", title="Разработка сайтов — лендинг, корпоративный сайт | promtchi",
    meta="Разработка сайтов для бизнеса в Ташкенте: лендинг, корпоративный сайт, интернет-магазин и веб-приложение. Быстро, адаптивно, готово к SEO. MVP — за 14 дней.",
    value="Создаём быстрый, адаптивный и находимый в поиске сайт или веб-приложение для вашего бизнеса — полный цикл от дизайна до развёртывания на сервере.",
    for_whom="Для предпринимателей, выводящих бизнес в онлайн, компаний, которым нужен корпоративный сайт, а также команд с потребностью в интернет-магазине или внутреннем веб-приложении.",
    problem="Многие компании работают с устаревшим, медленным или неадаптивным сайтом — это отпугивает клиентов и снижает позиции в Google.",
    solution="Строим сайт на современном стеке с быстрой отдачей страниц — каждая страница готова к SEO, mobile-first и соответствует требованиям Core Web Vitals.",
    includes=["Лендинг или многостраничный корпоративный сайт", "Интернет-магазин (каталог, корзина, интеграция оплаты)", "Веб-приложение (личный кабинет, панель заказов)", "Админ-панель — управляйте контентом сами", "Домен, хостинг и развёртывание на сервере", "Основы SEO: метатеги, sitemap, оптимизация скорости"],
    features=["Mobile-first, адаптивный дизайн", "Быстрая загрузка (оптимизация изображений/шрифтов/JS)", "Управление контентом через админ-панель", "Форма связи и уведомления в Telegram/email", "HTTPS, заголовки безопасности"],
    tech=["FastAPI / Django", "PostgreSQL", "JavaScript", "Server-side rendering"],
    price_note="Лендинг — от $300, многостраничный корпоративный сайт или веб-приложение — от $800 (см. раздел «Цены»). Точная стоимость зависит от объёма проекта.",
    faq=[("Сколько времени занимает разработка сайта?","Лендинг обычно готов за 7–14 дней, многостраничный сайт или веб-приложение — за 14–25 дней."),
         ("Смогу ли я сам редактировать сайт?","Да — через админ-панель вы меняете текст, изображения и другой контент без участия разработчика.")]),
  "en": dict(nav="Web & App", h1="Web Development", title="Web Development — landing page, corporate website | promtchi",
    meta="Web development for business in Tashkent: landing pages, corporate websites, online stores and web apps. Fast, mobile-friendly, SEO-ready. MVP in 14 days.",
    value="We build a fast, mobile-friendly, search-findable website or web app for your business — the full cycle from design to server deployment.",
    for_whom="For entrepreneurs bringing their business online, companies that need a corporate website, and teams that need an online store or internal web app.",
    problem="Many businesses run on an outdated, slow, or non-mobile-friendly website — that drives customers away and hurts Google rankings.",
    solution="We build on a modern stack with fast page delivery — every page is SEO-ready, mobile-first, and meets Core Web Vitals requirements.",
    includes=["Landing page or multi-page corporate website", "Online store (catalog, cart, payment integration)", "Web app (client dashboard, order management panel)", "Admin panel — manage content yourself", "Domain, hosting and server deployment", "SEO basics: meta tags, sitemap, speed optimization"],
    features=["Mobile-first, responsive design", "Fast loading (optimized images/fonts/JS)", "Content management via admin panel", "Contact form with Telegram/email notifications", "HTTPS, security headers"],
    tech=["FastAPI / Django", "PostgreSQL", "JavaScript", "Server-side rendering"],
    price_note="A landing page starts from $300, a multi-page corporate website or web app from $800 (see the Pricing section). Exact pricing depends on project scope.",
    faq=[("How long does a website take to build?","A landing page usually takes 7–14 days; a multi-page website or web app takes 14–25 days."),
         ("Can I edit the site myself?","Yes — the admin panel lets you change text, images and other content without a developer.")]),
},
"mobile": {
  "uz": dict(nav="Mobil ilova", h1="Mobil ilova yaratish", title="Mobil ilova yaratish — Android va iOS | promtchi",
    meta="Toshkentda biznes uchun mobil ilova ishlab chiqish: Android va iOS, bitta kod bazasida (Flutter). Tez, barqaror, App Store/Google Play'ga joylashtirish bilan.",
    value="Bitta kod bazasidan Android va iOS uchun tez, barqaror mobil ilova yasaymiz — dizayndan do'konlarga joylashgacha.",
    for_whom="Mobil orqali xizmat ko'rsatmoqchi bo'lgan bizneslar, buyurtma/rezervatsiya ilovasi kerak bo'lgan kompaniyalar, mavjud web mahsulotni mobilga olib chiqmoqchi bo'lganlar uchun.",
    problem="Faqat veb-sayt orqali xizmat ko'rsatish ba'zi mijozlarni (doimiy foydalanuvchilar, push-bildirishnoma kerak bo'lganlar) qamrab ololmaydi.",
    solution="Flutter asosida bitta kod bazasidan ikkala platforma uchun ilova yasaymiz — bu ishlab chiqishni tezlashtiradi va ikkala versiyani sinxron ushlab turadi.",
    includes=["UI/UX dizayn (Figma prototip)", "Android va iOS ilova (Flutter)", "Backend API va autentifikatsiya", "Push-bildirishnomalar", "App Store va Google Play'ga joylashtirish", "Ishga tushirilgach texnik yordam"],
    features=["Bitta kod — ikkala platforma", "Offline rejim (kerak bo'lsa)", "Push-bildirishnoma", "Backend bilan real vaqt sinxronizatsiya", "Analitika integratsiyasi"],
    tech=["Flutter", "Python / FastAPI backend", "PostgreSQL", "Firebase (push uchun)"],
    price_note="Mobil ilova narxi funksionallik hajmiga qarab belgilanadi — aniq baho texnik topshiriqdan so'ng 3 kun ichida taqdim etiladi.",
    faq=[("Faqat Android yoki faqat iOS qilib bo'ladimi?","Ha, xohishga ko'ra bitta platforma uchun ham ishlab chiqamiz — bu odatda arzonroq va tezroq."),
         ("Ilova narxi qanday hisoblanadi?","Ekranlar soni, backend murakkabligi va integratsiyalarga (to'lov, xarita va h.k.) qarab.")]),
  "ru": dict(nav="Мобильное приложение", h1="Разработка мобильных приложений", title="Разработка мобильных приложений — Android и iOS | promtchi",
    meta="Разработка мобильных приложений для бизнеса в Ташкенте: Android и iOS на едином кодовой базе (Flutter). Быстро, стабильно, с публикацией в App Store/Google Play.",
    value="Создаём быстрое и стабильное мобильное приложение для Android и iOS из единой кодовой базы — от дизайна до публикации в сторах.",
    for_whom="Для бизнеса, который хочет обслуживать клиентов через мобильное приложение, компаний с потребностью в заказах/бронировании, а также тех, кто хочет перенести веб-продукт в мобильный формат.",
    problem="Обслуживание только через сайт не охватывает часть аудитории — постоянных пользователей и тех, кому нужны push-уведомления.",
    solution="Разрабатываем на Flutter из единой кодовой базы для обеих платформ — это ускоряет разработку и держит версии синхронными.",
    includes=["UI/UX дизайн (прототип в Figma)", "Приложение для Android и iOS (Flutter)", "Backend API и аутентификация", "Push-уведомления", "Публикация в App Store и Google Play", "Техническая поддержка после запуска"],
    features=["Единый код — обе платформы", "Офлайн-режим (при необходимости)", "Push-уведомления", "Синхронизация с backend в реальном времени", "Интеграция аналитики"],
    tech=["Flutter", "Python / FastAPI backend", "PostgreSQL", "Firebase (для push)"],
    price_note="Стоимость мобильного приложения зависит от объёма функциональности — точная оценка предоставляется в течение 3 дней после технического задания.",
    faq=[("Можно сделать только для Android или только для iOS?","Да, по желанию разрабатываем и для одной платформы — это обычно дешевле и быстрее."),
         ("Как рассчитывается стоимость приложения?","В зависимости от количества экранов, сложности backend и интеграций (оплата, карты и т.д.).")]),
  "en": dict(nav="Mobile App", h1="Mobile App Development", title="Mobile App Development — Android and iOS | promtchi",
    meta="Mobile app development for business in Tashkent: Android and iOS from a single codebase (Flutter). Fast, stable, with App Store/Google Play publishing.",
    value="We build a fast, stable mobile app for Android and iOS from a single codebase — from design to store publishing.",
    for_whom="For businesses that want to serve customers through a mobile app, companies that need ordering/booking, and teams bringing an existing web product to mobile.",
    problem="Serving customers only through a website misses part of the audience — repeat users and anyone who needs push notifications.",
    solution="We build on Flutter from a single codebase for both platforms — this speeds up development and keeps both versions in sync.",
    includes=["UI/UX design (Figma prototype)", "Android and iOS app (Flutter)", "Backend API and authentication", "Push notifications", "App Store and Google Play publishing", "Technical support after launch"],
    features=["One codebase — both platforms", "Offline mode (when needed)", "Push notifications", "Real-time sync with backend", "Analytics integration"],
    tech=["Flutter", "Python / FastAPI backend", "PostgreSQL", "Firebase (for push)"],
    price_note="Mobile app pricing depends on the scope of functionality — an exact quote is provided within 3 days after the technical spec.",
    faq=[("Can you build for only Android or only iOS?","Yes, on request we also develop for a single platform — usually cheaper and faster."),
         ("How is the app price calculated?","Based on the number of screens, backend complexity, and integrations (payments, maps, etc.).")]),
},
"crm": {
  "uz": dict(nav="CRM tizim", h1="CRM tizim yaratish", title="CRM tizim yaratish — sotuv bo'limi uchun | promtchi",
    meta="Biznes uchun CRM tizim: lead'dan to'lovgacha butun sotuv voronkasini boshqaring. Kanban, Telegram sinxronizatsiya, statistika. Real loyihada sinalgan.",
    value="Lead kelishidan to'lov qabul qilishgacha butun sotuv jarayonini bitta tizimga yig'amiz — sotuv bo'limingiz endi Excel yoki daftarga muhtoj bo'lmaydi.",
    for_whom="Sotuv bo'limi bo'lgan, ko'p lead qabul qiladigan yoki mijozlar bilan ishlashni tizimlashtirishni istagan bizneslar uchun — savdo, xizmat ko'rsatish, optom savdo.",
    problem="Lead'lar qo'lda yig'iladi, sotuv jarayoni tarqoq bo'ladi (Excel, Telegram, daftar) va kim qaysi bosqichda ekanini kuzatib bo'lmaydi.",
    solution="Kanban-uslubidagi bosqichli voronka (yangi → aloqa → uchrashuv → TZ → to'lov → yakun) qurib, har bir lead'ning tarixi, izohlari va biriktirilgan menejeri bitta joyda saqlanadi.",
    includes=["Kanban doska (bosqichlar, drag&drop)", "Lead kartasi: tarix, izohlar, biriktirish", "Qidiruv va filtrlar", "Telegram orqali ikki tomonlama bildirishnoma va bosqich almashtirish", "Statistika: voronka, konversiya, menejerlar kesimi, CSV eksport", "Rollar: menejer o'z lead'larini, admin barchasini ko'radi"],
    features=["Real vaqtli Kanban doska", "Telegram integratsiyasi (bildirishnoma + bosqich boshqaruvi)", "Dublikat lead'larni avtomatik aniqlash", "Statistika va CSV eksport", "Ko'p foydalanuvchili rollar tizimi"],
    tech=["FastAPI", "PostgreSQL", "Telegram Bot API", "Redis"],
    price_note="Individual CRM tizimi \"Maxsus\" paket doirasida — narx kelishilgan holda, kompaniya jarayonlariga moslashtirilib hisoblanadi.",
    faq=[("Mavjud CRM (AmoCRM, Bitrix24)ga integratsiya qila olasizmi?","Ha — real loyihalarimizda AmoCRM, Bitrix24, UTEL va Meta Ads bilan real vaqtli sinxronizatsiyani qurganmiz."),
         ("CRM Telegram bilan qanday ishlaydi?","Yangi lead kelganda Telegram guruhiga xabar boradi, tugmalar orqali bosqichni o'zgartirish mumkin — sayt va Telegram doim sinxron.")]),
  "ru": dict(nav="CRM система", h1="Разработка CRM системы", title="Разработка CRM системы — для отдела продаж | promtchi",
    meta="CRM система для бизнеса: управляйте всей воронкой продаж от лида до оплаты. Канбан, синхронизация с Telegram, статистика. Проверено на реальном проекте.",
    value="Объединяем весь процесс продаж — от поступления лида до получения оплаты — в единой системе: отдел продаж больше не зависит от Excel или блокнота.",
    for_whom="Для бизнеса с отделом продаж, большим потоком лидов или желанием систематизировать работу с клиентами — продажи, услуги, оптовая торговля.",
    problem="Лиды собираются вручную, процесс продаж разрознен (Excel, Telegram, блокнот), и невозможно отследить, на каком этапе находится каждый клиент.",
    solution="Строим поэтапную Kanban-воронку (новый → контакт → встреча → ТЗ → оплата → завершение), где история, комментарии и ответственный менеджер каждого лида хранятся в одном месте.",
    includes=["Kanban-доска (этапы, drag&drop)", "Карточка лида: история, комментарии, назначение", "Поиск и фильтры", "Двусторонние уведомления и смена этапа через Telegram", "Статистика: воронка, конверсия, срез по менеджерам, экспорт в CSV", "Роли: менеджер видит своих лидов, админ — всех"],
    features=["Kanban-доска в реальном времени", "Интеграция с Telegram (уведомления + управление этапами)", "Автоматическое обнаружение дублей лидов", "Статистика и экспорт в CSV", "Многопользовательская система ролей"],
    tech=["FastAPI", "PostgreSQL", "Telegram Bot API", "Redis"],
    price_note="Индивидуальная CRM — в рамках пакета «Индивидуальный»: стоимость рассчитывается по договорённости с учётом процессов вашей компании.",
    faq=[("Можно интегрировать с существующей CRM (AmoCRM, Bitrix24)?","Да — в реальных проектах мы строили синхронизацию в реальном времени с AmoCRM, Bitrix24, UTEL и Meta Ads."),
         ("Как CRM работает с Telegram?","При поступлении нового лида приходит сообщение в Telegram-группу, этап можно менять кнопками — сайт и Telegram всегда синхронизированы.")]),
  "en": dict(nav="CRM System", h1="CRM Development", title="CRM Development — for your sales team | promtchi",
    meta="Custom CRM system for business: manage the entire sales pipeline from lead to payment. Kanban board, Telegram sync, analytics. Proven on a real project.",
    value="We bring the whole sales process — from lead to payment — into one system, so your sales team no longer depends on spreadsheets or notebooks.",
    for_whom="For businesses with a sales team, a high lead volume, or a need to systemize client management — sales, services, wholesale trade.",
    problem="Leads are collected manually, the sales process is fragmented (spreadsheets, Telegram, notebooks), and it's impossible to track which stage each client is at.",
    solution="We build a staged Kanban pipeline (new → contacted → meeting → spec → payment → closed) where each lead's history, notes and assigned manager live in one place.",
    includes=["Kanban board (stages, drag & drop)", "Lead card: history, notes, assignment", "Search and filters", "Two-way Telegram notifications and stage changes", "Analytics: funnel, conversion, per-manager breakdown, CSV export", "Roles: managers see their own leads, admins see all"],
    features=["Real-time Kanban board", "Telegram integration (notifications + stage control)", "Automatic duplicate-lead detection", "Analytics and CSV export", "Multi-user role system"],
    tech=["FastAPI", "PostgreSQL", "Telegram Bot API", "Redis"],
    price_note="A custom CRM falls under the \"Custom\" package — pricing is agreed individually based on your company's processes.",
    faq=[("Can you integrate with an existing CRM (AmoCRM, Bitrix24)?","Yes — on real projects we've built real-time sync with AmoCRM, Bitrix24, UTEL and Meta Ads."),
         ("How does the CRM work with Telegram?","When a new lead comes in, a message is sent to the Telegram group, and the stage can be changed with buttons — the site and Telegram stay in sync.")]),
},
"erp": {
  "uz": dict(nav="ERP tizim", h1="ERP tizim ishlab chiqish", title="ERP tizim ishlab chiqish — moliya, ombor, KPI | promtchi",
    meta="Biznes uchun ERP tizim: moliya, ombor, xodimlar va KPI'ni bitta dashboard'da boshqaring. Real vaqtli hisobotlar va avtomatlashtirilgan hisob-kitob.",
    value="Kompaniyangizning moliya, ombor, xodimlar va sotuv jarayonlarini bitta markazlashgan tizimga birlashtirib, real vaqtli dashboard orqali nazorat qilish imkonini beramiz.",
    for_whom="Ombori, ko'p xodimi yoki murakkab moliyaviy jarayoni bo'lgan o'rta va yirik bizneslar — savdo, ishlab chiqarish, logistika kompaniyalari uchun.",
    problem="Moliya, ombor va xodimlar bo'yicha ma'lumotlar turli fayllar va tizimlarda tarqoq bo'ladi — hisobot tayyorlash kunlab vaqt oladi va xatolikka moyil.",
    solution="Barcha modullarni (moliya, ombor, xodimlar, KPI) bitta ma'lumotlar bazasiga bog'lab, har bir operatsiya avtomatik hisobotga tushadigan tizim quramiz.",
    includes=["Moliya moduli: tushum, xarajat, ish haqi", "Ombor va mahsulot nazorati", "KPI va bonuslarni avtomatik hisoblash", "Real vaqtli dashboard", "API — boshqa tizimlar bilan integratsiya", "Ma'lumotlarni himoyalash va zaxira nusxalash"],
    features=["Markazlashgan ma'lumotlar bazasi", "Real vaqtli hisobot va dashboard", "Rol asosidagi kirish huquqlari", "Tashqi tizimlar bilan API integratsiya", "Avtomatik zaxira nusxalash"],
    tech=["Django DRF", "PostgreSQL", "Redis", "Docker"],
    price_note="ERP tizim \"Maxsus\" paket doirasida ishlab chiqiladi — narx modullar soni va integratsiyalarga qarab kelishiladi.",
    faq=[("ERP va CRM farqi nimada?","CRM — mijozlar va sotuv jarayoni bilan ishlaydi; ERP — moliya, ombor, xodimlar kabi butun kompaniya resurslarini boshqaradi. Ko'pincha ikkalasi birga integratsiya qilinadi."),
         ("Mavjud buxgalteriya tizimi bilan ishlay oladimi?","Ha, API orqali mavjud tizimlar (buxgalteriya, ombor dasturlari)ga integratsiya qilamiz.")]),
  "ru": dict(nav="ERP система", h1="Разработка ERP системы", title="Разработка ERP системы — финансы, склад, KPI | promtchi",
    meta="ERP система для бизнеса: управляйте финансами, складом, персоналом и KPI в едином дашборде. Отчёты в реальном времени и автоматизированные расчёты.",
    value="Объединяем финансы, склад, персонал и продажи вашей компании в единой централизованной системе с контролем через дашборд в реальном времени.",
    for_whom="Для среднего и крупного бизнеса со складом, большим штатом или сложными финансовыми процессами — торговые, производственные и логистические компании.",
    problem="Данные по финансам, складу и персоналу разбросаны по разным файлам и системам — подготовка отчёта занимает дни и подвержена ошибкам.",
    solution="Связываем все модули (финансы, склад, персонал, KPI) в единой базе данных — каждая операция автоматически попадает в отчётность.",
    includes=["Модуль финансов: доходы, расходы, зарплата", "Контроль склада и товаров", "Автоматический расчёт KPI и бонусов", "Дашборд в реальном времени", "API — интеграция с другими системами", "Защита данных и резервное копирование"],
    features=["Централизованная база данных", "Отчётность и дашборд в реальном времени", "Права доступа на основе ролей", "API-интеграция с внешними системами", "Автоматическое резервное копирование"],
    tech=["Django DRF", "PostgreSQL", "Redis", "Docker"],
    price_note="ERP-система разрабатывается в рамках пакета «Индивидуальный» — стоимость согласуется исходя из количества модулей и интеграций.",
    faq=[("В чём разница между ERP и CRM?","CRM работает с клиентами и процессом продаж; ERP управляет ресурсами всей компании — финансами, складом, персоналом. Часто их интегрируют вместе."),
         ("Можно интегрировать с существующей бухгалтерской системой?","Да, через API интегрируем с существующими системами (бухгалтерия, складские программы).")]),
  "en": dict(nav="ERP System", h1="ERP Development", title="ERP Development — finance, inventory, KPI | promtchi",
    meta="ERP system for business: manage finance, inventory, staff and KPIs in one real-time dashboard. Automated reporting and calculations.",
    value="We bring your company's finance, inventory, staff and sales processes into one centralized system with real-time dashboard oversight.",
    for_whom="For medium and large businesses with a warehouse, a large team, or complex financial processes — trading, manufacturing and logistics companies.",
    problem="Finance, inventory and staff data is scattered across different files and systems — building a report takes days and is error-prone.",
    solution="We link every module (finance, inventory, staff, KPI) to a single database, so every operation flows automatically into reporting.",
    includes=["Finance module: revenue, expenses, payroll", "Inventory and stock control", "Automatic KPI and bonus calculation", "Real-time dashboard", "API for integration with other systems", "Data protection and backups"],
    features=["Centralized database", "Real-time reporting and dashboard", "Role-based access control", "API integration with external systems", "Automatic backups"],
    tech=["Django DRF", "PostgreSQL", "Redis", "Docker"],
    price_note="An ERP system is built under the \"Custom\" package — pricing is agreed based on the number of modules and integrations.",
    faq=[("What's the difference between ERP and CRM?","CRM handles clients and the sales process; ERP manages the whole company's resources — finance, inventory, staff. The two are often integrated together."),
         ("Can it work with an existing accounting system?","Yes, we integrate with existing systems (accounting, warehouse software) via API.")]),
},
"ai": {
  "uz": dict(nav="AI yechimlar", h1="AI yechimlar ishlab chiqish", title="AI chatbot va sun'iy intellekt yechimlari | promtchi",
    meta="Biznes uchun AI yechimlar: chatbot, ovozni matnga aylantirish (STT), kontent generatsiya. O'zbek tili uchun optimallashtirilgan real loyihada sinalgan.",
    value="Sun'iy intellekt yordamida mijozlarga xizmat ko'rsatishni, kontentni va jarayonlarni avtomatlashtiramiz — real loyihada o'zbek tili uchun maxsus optimallashtirilgan.",
    for_whom="Mijozlar bilan ko'p muloqot qiluvchi bizneslar, ovozni matnga aylantirish kerak bo'lgan ilovalar, kontent yoki qo'llab-quvvatlash jarayonini avtomatlashtirmoqchi bo'lganlar uchun.",
    problem="Qo'llab-quvvatlash jamoasi takroriy savollarga vaqt sarflaydi, mavjud ovoz-matn yechimlari esa o'zbek tilida past aniqlik beradi.",
    solution="Vazifaga mos AI yechim (chatbot, STT modeli yoki kontent-generatsiya) qurib, uni saytingiz, Telegram botingiz yoki mobil ilovangizga integratsiya qilamiz.",
    includes=["AI chatbot (savol-javob, buyurtma qabul qilish)", "Ovozni matnga aylantirish (STT) integratsiyasi", "Kontent generatsiya yordamchisi", "Saytga yoki Telegram botga integratsiya", "Model sozlash va aniqlikni oshirish"],
    features=["O'zbek tili uchun moslashtirilgan modellar", "Saytga/botга tez integratsiya", "Doimiy aniqlikni yaxshilash", "Mobil va web platformalar bilan ishlaydi"],
    tech=["Python", "ASR pipeline", "Flutter (mobil interfeys uchun)"],
    price_note="AI yechim narxi vazifa murakkabligiga bog'liq — aniq baho konsultatsiyadan so'ng beriladi.",
    faq=[("O'zbek tilida ishlaydigan AI yechimingiz bormi?","Ha — Notiq AI loyihamizda o'zbek tiliga moslashtirilgan ovozni matnga aylantirish (STT) modelini ishlab chiqqanmiz."),
         ("AI chatbotni Telegram yoki saytga ulash mumkinmi?","Ha, chatbot istalgan kanalga (sayt, Telegram, mobil ilova) integratsiya qilinadi.")]),
  "ru": dict(nav="AI-решения", h1="Разработка AI-решений", title="AI-чат-боты и AI-решения для бизнеса | promtchi",
    meta="AI-решения для бизнеса: чат-боты, распознавание речи (STT), генерация контента. Проверено на реальном проекте, оптимизировано для узбекского языка.",
    value="Автоматизируем обслуживание клиентов, контент и процессы с помощью искусственного интеллекта — проверено на реальном проекте с оптимизацией под узбекский язык.",
    for_whom="Для бизнеса с большим объёмом общения с клиентами, приложений, которым нужно распознавание речи, а также тех, кто хочет автоматизировать контент или поддержку.",
    problem="Команда поддержки тратит время на повторяющиеся вопросы, а существующие решения для речи в текст дают низкую точность на узбекском языке.",
    solution="Строим AI-решение под конкретную задачу (чат-бот, модель STT или генерация контента) и интегрируем его в сайт, Telegram-бота или мобильное приложение.",
    includes=["AI-чат-бот (вопросы-ответы, приём заказов)", "Интеграция распознавания речи (STT)", "Помощник для генерации контента", "Интеграция с сайтом или Telegram-ботом", "Настройка модели и повышение точности"],
    features=["Модели, адаптированные под узбекский язык", "Быстрая интеграция с сайтом/ботом", "Постоянное улучшение точности", "Работает с мобильными и веб-платформами"],
    tech=["Python", "ASR pipeline", "Flutter (для мобильного интерфейса)"],
    price_note="Стоимость AI-решения зависит от сложности задачи — точная оценка даётся после консультации.",
    faq=[("Есть ли у вас AI-решение для узбекского языка?","Да — в проекте Notiq AI мы разработали модель распознавания речи (STT), адаптированную под узбекский язык."),
         ("Можно подключить AI-чат-бот к Telegram или сайту?","Да, чат-бот интегрируется в любой канал (сайт, Telegram, мобильное приложение).")]),
  "en": dict(nav="AI Solutions", h1="AI Solution Development", title="AI Chatbots and Artificial Intelligence Solutions | promtchi",
    meta="AI solutions for business: chatbots, speech-to-text (STT), content generation. Proven on a real project, optimized for the Uzbek language.",
    value="We automate customer service, content and processes with artificial intelligence — proven on a real project with Uzbek-language optimization.",
    for_whom="For businesses with a high volume of customer communication, apps that need speech-to-text, and anyone looking to automate content or support.",
    problem="Support teams spend time on repetitive questions, and existing speech-to-text solutions give low accuracy in Uzbek.",
    solution="We build an AI solution tailored to the task (chatbot, STT model or content generation) and integrate it into your website, Telegram bot or mobile app.",
    includes=["AI chatbot (Q&A, order intake)", "Speech-to-text (STT) integration", "Content generation assistant", "Integration into a website or Telegram bot", "Model tuning and accuracy improvement"],
    features=["Models adapted for the Uzbek language", "Fast integration into a site/bot", "Ongoing accuracy improvements", "Works with mobile and web platforms"],
    tech=["Python", "ASR pipeline", "Flutter (for mobile interface)"],
    price_note="AI solution pricing depends on task complexity — an exact quote is given after a consultation.",
    faq=[("Do you have an AI solution that works in Uzbek?","Yes — on our Notiq AI project we built a speech-to-text (STT) model adapted for the Uzbek language."),
         ("Can an AI chatbot connect to Telegram or a website?","Yes, the chatbot can be integrated into any channel (website, Telegram, mobile app).")]),
},
"telegram-bot": {
  "uz": dict(nav="Telegram bot", h1="Telegram bot yaratish", title="Telegram bot yaratish — buyurtma, CRM, bildirishnoma | promtchi",
    meta="Biznes uchun Telegram bot dasturlash: buyurtma qabul qilish, avtomatik javob, CRM bilan ikki tomonlama sinxronizatsiya. Real loyihalarda sinalgan.",
    value="Buyurtma qabul qilish, mijozlarga avtomatik javob berish va CRM bilan real vaqtli sinxron ishlaydigan Telegram bot quramiz.",
    for_whom="Telegram orqali buyurtma yoki murojaat qabul qiladigan bizneslar, sotuv jamoasi Telegramda ishlaydigan kompaniyalar uchun.",
    problem="Botlar odatda faqat oddiy avtojavob beradi va CRM yoki sayt bilan bog'lanmaydi — menejer ma'lumotni qo'lda ko'chirib yurishga majbur bo'ladi.",
    solution="Botni to'g'ridan-to'g'ri CRM voronkasiga ulaymiz — yangi lead kelganda Telegram guruhiga xabar boradi, tugma orqali bosqich o'zgartiriladi va sayt bilan sinxron qoladi.",
    includes=["Bot logikasi va buyruqlar (aiogram)", "CRM bilan ikki tomonlama sinxronizatsiya", "Guruh/kanalga avtomatik bildirishnoma", "Admin uchun boshqaruv buyruqlari", "Serverga joylashtirish (webhook/polling)"],
    features=["Ikki tomonlama CRM sinxronizatsiyasi", "Inline tugmalar orqali bosqich boshqaruvi", "Guruh va shaxsiy chatlarga bildirishnoma", "Yuqori yuklamaga chidamli navbat tizimi"],
    tech=["aiogram 3", "Python", "PostgreSQL", "Redis"],
    price_note="Oddiy Telegram bot \"Boshlang'ich\" paketga kiradi (300$ dan); CRM'ga to'liq ulangan professional bot \"Standart\" paket doirasida (800$ dan).",
    faq=[("Bot CRM bilan qanday ishlaydi?","Yangi ariza kelganda bot avtomatik xabar yuboradi va tugmalar orqali bosqichni o'zgartirish imkonini beradi — ikki tomonlama sinxron."),
         ("Botni mavjud guruhimizga ulash mumkinmi?","Ha, bot mavjud Telegram guruhi yoki kanalingizga qo'shiladi.")]),
  "ru": dict(nav="Telegram-бот", h1="Разработка Telegram-ботов", title="Разработка Telegram-ботов — заказы, CRM, уведомления | promtchi",
    meta="Разработка Telegram-ботов для бизнеса: приём заказов, автоответы, двусторонняя синхронизация с CRM. Проверено на реальных проектах.",
    value="Создаём Telegram-бота для приёма заказов, автоматических ответов клиентам и синхронизации с CRM в реальном времени.",
    for_whom="Для бизнеса, принимающего заказы или обращения через Telegram, и компаний, чей отдел продаж работает в Telegram.",
    problem="Обычные боты дают только простые автоответы и не связаны с CRM или сайтом — менеджеру приходится вручную переносить данные.",
    solution="Подключаем бота напрямую к воронке CRM — при поступлении нового лида приходит сообщение в Telegram-группу, этап меняется кнопкой и остаётся синхронным с сайтом.",
    includes=["Логика бота и команды (aiogram)", "Двусторонняя синхронизация с CRM", "Автоматические уведомления в группу/канал", "Команды управления для администратора", "Развёртывание на сервере (webhook/polling)"],
    features=["Двусторонняя синхронизация с CRM", "Управление этапами через inline-кнопки", "Уведомления в группы и личные чаты", "Устойчивая к нагрузке система очередей"],
    tech=["aiogram 3", "Python", "PostgreSQL", "Redis"],
    price_note="Простой Telegram-бот входит в пакет «Стартовый» (от $300); профессиональный бот с полной интеграцией CRM — в пакете «Стандарт» (от $800).",
    faq=[("Как бот работает с CRM?","При поступлении новой заявки бот автоматически отправляет сообщение и позволяет менять этап кнопками — двусторонняя синхронизация."),
         ("Можно подключить бота к нашей существующей группе?","Да, бот добавляется в вашу существующую Telegram-группу или канал.")]),
  "en": dict(nav="Telegram Bot", h1="Telegram Bot Development", title="Telegram Bot Development — orders, CRM, notifications | promtchi",
    meta="Telegram bot development for business: order intake, auto-replies, two-way CRM sync. Proven on real projects.",
    value="We build a Telegram bot for order intake, automatic customer replies, and real-time synchronization with your CRM.",
    for_whom="For businesses that take orders or inquiries via Telegram, and companies whose sales team works inside Telegram.",
    problem="Ordinary bots only give simple auto-replies and aren't connected to a CRM or website — managers end up copying data by hand.",
    solution="We connect the bot directly to the CRM pipeline — when a new lead arrives, a message goes to the Telegram group, the stage can be changed with a button, and it stays in sync with the website.",
    includes=["Bot logic and commands (aiogram)", "Two-way CRM synchronization", "Automatic notifications to a group/channel", "Admin management commands", "Server deployment (webhook/polling)"],
    features=["Two-way CRM synchronization", "Stage control via inline buttons", "Notifications to groups and personal chats", "Load-resilient queue system"],
    tech=["aiogram 3", "Python", "PostgreSQL", "Redis"],
    price_note="A basic Telegram bot is part of the \"Starter\" package (from $300); a professional bot with full CRM integration is part of \"Standard\" (from $800).",
    faq=[("How does the bot work with the CRM?","When a new lead arrives, the bot automatically sends a message and lets you change the stage with buttons — fully two-way synced."),
         ("Can the bot connect to our existing group?","Yes, the bot can be added to your existing Telegram group or channel.")]),
},
"automation": {
  "uz": dict(nav="Avtomatlashtirish", h1="Biznes jarayonlarini avtomatlashtirish", title="Avtomatlashtirish — sotuv, ombor, hisobot | promtchi",
    meta="Sotuv, ombor va hisobotlarni avtomatlashtirish: lead'dan to'lovgacha qo'lda ishlarni yo'qotamiz. Real loyihada ~70% qo'lda ishni kamaytirgan yechim.",
    value="Qo'lda bajariladigan takroriy jarayonlarni (lead yig'ish, hisobot, bildirishnoma) avtomatlashtirib, jamoangiz vaqtini asosiy ishga yo'naltiramiz.",
    for_whom="Sotuv jarayoni tarqoq, hisobotlar qo'lda tayyorlanadigan yoki bir nechta tizim (CRM, to'lov, ombor) orasida qo'lda ma'lumot ko'chiriladigan bizneslar uchun.",
    problem="Lead qo'lda yig'iladi, turli tizimlar (sayt, CRM, to'lov, ombor) bir-biri bilan gaplashmaydi — bu vaqt yo'qotadi va xatolarga olib keladi.",
    solution="Lead → CRM → to'lov → hisobot zanjirini yagona avtomatlashtirilgan tizimga bog'laymiz — har bir voqea (yangi buyurtma, to'lov, qarzdorlik) avtomatik boshqa tizimlarga uzatiladi.",
    includes=["Lead oqimini avtomatlashtirish (sayt/bot → CRM)", "To'lov tizimi integratsiyasi", "Avtomatik Telegram/email/SMS bildirishnoma", "Tashqi tizimlar (AmoCRM, Bitrix24 va h.k.) bilan sinxronizatsiya", "Avtomatik hisobot va dashboard"],
    features=["Tizimlar orasida real vaqtli sinxronizatsiya", "Avtomatik bildirishnoma zanjiri", "Qo'lda ma'lumot kiritishni kamaytirish", "Xatoliklarni kamaytiruvchi tekshiruvlar"],
    tech=["FastAPI", "PostgreSQL", "Telegram Bot API", "Redis", "Docker"],
    price_note="Avtomatlashtirish loyihasi hajmiga qarab \"Standart\" yoki \"Maxsus\" paket doirasida baholanadi.",
    faq=[("Avtomatlashtirish real natija berganmi?","Ha — Chindan Group loyihasida lead'dan to'lovgacha bo'lgan zanjirni avtomatlashtirib, qo'lda ishlarni ~70% kamaytirdik."),
         ("Qaysi tizimlarni bog'lay olasiz?","Sayt, Telegram bot, CRM (shu jumladan AmoCRM/Bitrix24), to'lov tizimlari va ombor dasturlarini bitta oqimga bog'laymiz.")]),
  "ru": dict(nav="Автоматизация", h1="Автоматизация бизнес-процессов", title="Автоматизация — продажи, склад, отчётность | promtchi",
    meta="Автоматизация продаж, склада и отчётности: убираем ручной труд на пути от лида до оплаты. На реальном проекте сократили ручную работу примерно на 70%.",
    value="Автоматизируем повторяющиеся ручные процессы (сбор лидов, отчётность, уведомления), освобождая время вашей команды для основной работы.",
    for_whom="Для бизнеса с разрозненным процессом продаж, ручной подготовкой отчётов или переносом данных вручную между несколькими системами (CRM, оплата, склад).",
    problem="Лиды собираются вручную, разные системы (сайт, CRM, оплата, склад) не связаны между собой — это отнимает время и приводит к ошибкам.",
    solution="Связываем цепочку лид → CRM → оплата → отчётность в единую автоматизированную систему — каждое событие (новый заказ, оплата, задолженность) автоматически передаётся в другие системы.",
    includes=["Автоматизация потока лидов (сайт/бот → CRM)", "Интеграция платёжной системы", "Автоматические уведомления в Telegram/email/SMS", "Синхронизация с внешними системами (AmoCRM, Bitrix24 и др.)", "Автоматическая отчётность и дашборд"],
    features=["Синхронизация систем в реальном времени", "Цепочка автоматических уведомлений", "Снижение ручного ввода данных", "Проверки, снижающие количество ошибок"],
    tech=["FastAPI", "PostgreSQL", "Telegram Bot API", "Redis", "Docker"],
    price_note="Стоимость автоматизации оценивается в рамках пакета «Стандарт» или «Индивидуальный» в зависимости от объёма проекта.",
    faq=[("Автоматизация дала реальный результат?","Да — в проекте Chindan Group мы автоматизировали цепочку от лида до оплаты и сократили ручную работу примерно на 70%."),
         ("Какие системы вы можете связать?","Сайт, Telegram-бот, CRM (включая AmoCRM/Bitrix24), платёжные системы и складские программы — в единый поток.")]),
  "en": dict(nav="Automation", h1="Business Process Automation", title="Business Automation — sales, inventory, reporting | promtchi",
    meta="Sales, inventory and reporting automation: eliminate manual work from lead to payment. Cut manual work by ~70% on a real project.",
    value="We automate repetitive manual processes (lead collection, reporting, notifications), freeing your team's time for the work that matters.",
    for_whom="For businesses with a fragmented sales process, manually-built reports, or manual data transfer between multiple systems (CRM, payments, inventory).",
    problem="Leads are collected manually, and different systems (website, CRM, payments, inventory) don't talk to each other — this wastes time and causes errors.",
    solution="We connect the lead → CRM → payment → reporting chain into one automated system — every event (a new order, a payment, an outstanding debt) is automatically passed to other systems.",
    includes=["Lead flow automation (site/bot → CRM)", "Payment system integration", "Automatic Telegram/email/SMS notifications", "Sync with external systems (AmoCRM, Bitrix24, etc.)", "Automatic reporting and dashboard"],
    features=["Real-time sync between systems", "Automated notification chains", "Reduced manual data entry", "Checks that reduce errors"],
    tech=["FastAPI", "PostgreSQL", "Telegram Bot API", "Redis", "Docker"],
    price_note="Automation projects are scoped under the \"Standard\" or \"Custom\" package depending on project size.",
    faq=[("Has automation delivered real results?","Yes — on the Chindan Group project we automated the chain from lead to payment and cut manual work by about 70%."),
         ("Which systems can you connect?","Website, Telegram bot, CRM (including AmoCRM/Bitrix24), payment systems and warehouse software — all into one flow.")]),
},
}
