"""3 ta soha bo'yicha yechim sahifasi (TZ 2-bo'lim: /yechimlar/savdo, /logistika,
/ishlab-chiqarish). Faqat real tajribamizga (Tizimly, Chindan Group orqali
tasdiqlangan CRM/ERP/avtomatlashtirish qobiliyati) asoslangan — soha bo'yicha
fake case yozilmagan, faqat qanday yordam bera olishimiz tasvirlangan."""

SOLUTION_KEYS = ["savdo", "logistika", "ishlab-chiqarish"]

SLUGS = {
    "savdo": {"uz": "savdo", "ru": "prodazhi", "en": "sales"},
    "logistika": {"uz": "logistika", "ru": "logistika", "en": "logistics"},
    "ishlab-chiqarish": {"uz": "ishlab-chiqarish", "ru": "proizvodstvo", "en": "manufacturing"},
}

SOLUTIONS = {
"savdo": {
  "uz": dict(nav="Savdo", h1="Savdo va optom savdo uchun yechimlar",
    title="Savdo uchun CRM va avtomatlashtirish yechimlari | promtchi",
    meta="Optom va chakana savdo uchun CRM, ombor va to'lov integratsiyasi. Real loyihada (Tizimly, Chindan Group) sinalgan yechimlar.",
    intro="Savdo bilan shug'ullanuvchi bizneslar uchun lead'dan to'lovgacha bo'lgan butun jarayonni — sotuv, ombor, mijozlar bazasi va hisobotni — bitta tizimga birlashtiramiz.",
    challenges=["Lead'lar va mijozlar ma'lumoti turli joyda (Excel, Telegram, daftar) tarqoq", "Ombor qoldig'i savdo bilan real vaqtda yangilanmaydi", "Hisobot va KPI qo'lda, kechikib tayyorlanadi", "Bir nechta savdo kanali (sayt, Telegram, do'kon) sinxron emas"],
    approach="CRM Kanban voronkasi orqali har bir mijoz va bitim bitta joyda kuzatiladi; savdo amalga oshganda ombor qoldig'i avtomatik yangilanadi; to'lov va qarzdorlik haqida Telegram orqali darhol xabar keladi.",
    services_ref=["crm", "erp", "automation", "telegram-bot"],
    case_ref=["tizimly", "chindan-group"],
    faq=[("Bir nechta savdo nuqtasi/kanalini bitta tizimga bog'lash mumkinmi?","Ha — Tizimly platformamizda savdo, ombor va moliyani bitta markazlashgan tizimga bog'laganmiz, 150 dan ortiq kompaniya foydalanmoqda."),
         ("Mavjud CRM (AmoCRM, Bitrix24) bilan ishlay olasizmi?","Ha, real loyihalarda AmoCRM, Bitrix24, UTEL va Meta Ads bilan real vaqtli sinxronizatsiya qurganmiz.")]),
  "ru": dict(nav="Продажи", h1="Решения для продаж и оптовой торговли",
    title="CRM и автоматизация для продаж | promtchi",
    meta="CRM, склад и интеграция оплаты для оптовой и розничной торговли. Решения, проверенные на реальных проектах (Tizimly, Chindan Group).",
    intro="Для бизнеса в сфере продаж объединяем весь процесс — от лида до оплаты: продажи, склад, базу клиентов и отчётность — в единой системе.",
    challenges=["Данные о лидах и клиентах разбросаны (Excel, Telegram, блокнот)", "Остатки склада не обновляются в реальном времени вместе с продажами", "Отчётность и KPI готовятся вручную и с задержкой", "Несколько каналов продаж (сайт, Telegram, магазин) не синхронизированы"],
    approach="Через Kanban-воронку CRM каждый клиент и сделка отслеживаются в одном месте; при продаже остатки склада обновляются автоматически; об оплатах и задолженностях мгновенно приходит уведомление в Telegram.",
    services_ref=["crm", "erp", "automation", "telegram-bot"],
    case_ref=["tizimly", "chindan-group"],
    faq=[("Можно ли объединить несколько точек/каналов продаж в одну систему?","Да — в платформе Tizimly мы объединили продажи, склад и финансы в единой централизованной системе, которой пользуются более 150 компаний."),
         ("Вы работаете с существующей CRM (AmoCRM, Bitrix24)?","Да, в реальных проектах мы строили синхронизацию в реальном времени с AmoCRM, Bitrix24, UTEL и Meta Ads.")]),
  "en": dict(nav="Sales", h1="Solutions for Sales & Wholesale Trade",
    title="CRM and Automation Solutions for Sales | promtchi",
    meta="CRM, inventory and payment integration for wholesale and retail. Solutions proven on real projects (Tizimly, Chindan Group).",
    intro="For sales-driven businesses, we bring the whole process — from lead to payment: sales, inventory, the client database and reporting — into one system.",
    challenges=["Lead and client data is scattered (spreadsheets, Telegram, notebooks)", "Warehouse stock isn't updated in real time alongside sales", "Reporting and KPIs are built manually and with delays", "Multiple sales channels (website, Telegram, store) aren't in sync"],
    approach="A CRM Kanban pipeline tracks every client and deal in one place; when a sale happens, warehouse stock updates automatically; payments and outstanding debt trigger instant Telegram notifications.",
    services_ref=["crm", "erp", "automation", "telegram-bot"],
    case_ref=["tizimly", "chindan-group"],
    faq=[("Can multiple sales points/channels be unified into one system?","Yes — on our Tizimly platform we unified sales, inventory and finance into one centralized system, now used by 150+ companies."),
         ("Do you work with an existing CRM (AmoCRM, Bitrix24)?","Yes, on real projects we've built real-time sync with AmoCRM, Bitrix24, UTEL and Meta Ads.")]),
},
"logistika": {
  "uz": dict(nav="Logistika", h1="Logistika va ombor uchun yechimlar",
    title="Logistika va ombor avtomatlashtirish yechimlari | promtchi",
    meta="Logistika va ombor jarayonlarini avtomatlashtirish: real vaqtli qoldiq nazorati, buyurtma kuzatuvi, Telegram bildirishnoma.",
    intro="Ombor va yetkazib berish jarayonlarini raqamlashtirib, qoldiq, buyurtma va yetkazib berish holatini real vaqtda kuzatish imkonini beramiz.",
    challenges=["Ombor qoldig'i qo'lda hisoblanadi va tez-tez xato beradi", "Buyurtma holati (yig'ish → jo'natish → yetkazish) kuzatilmaydi", "Turli manzillarga yetkazib berishni rejalashtirish qo'lda bajariladi", "Ombor va sotuv tizimlari o'zaro bog'lanmagan"],
    approach="ERP ombor modulini CRM/sotuv tizimi bilan bog'lab, har bir operatsiya (kirim, chiqim, jo'natish) avtomatik qoldiqqa ta'sir qiladigan, Telegram orqali holat haqida darhol xabar beradigan tizim quramiz.",
    services_ref=["erp", "automation", "telegram-bot"],
    case_ref=["tizimly"],
    faq=[("Ombor qoldig'ini savdo bilan avtomatik bog'lash mumkinmi?","Ha — Tizimly platformamizda har bir savdo ombor qoldig'ini avtomatik yangilaydi."),
         ("Yetkazib berish holatini mijozga avtomatik xabar qilish mumkinmi?","Ha, Telegram bot orqali buyurtma holati (yig'ildi, jo'natildi, yetkazildi) haqida avtomatik xabar yuborish mumkin.")]),
  "ru": dict(nav="Логистика", h1="Решения для логистики и склада",
    title="Автоматизация логистики и склада | promtchi",
    meta="Автоматизация складских и логистических процессов: контроль остатков в реальном времени, отслеживание заказов, уведомления в Telegram.",
    intro="Оцифровываем складские и логистические процессы, обеспечивая контроль остатков, заказов и статуса доставки в реальном времени.",
    challenges=["Остатки склада считаются вручную и часто с ошибками", "Статус заказа (сборка → отправка → доставка) не отслеживается", "Планирование доставки по разным адресам выполняется вручную", "Складская и торговая системы не связаны между собой"],
    approach="Связываем модуль склада ERP с CRM/системой продаж — каждая операция (приход, расход, отправка) автоматически влияет на остатки, а статус мгновенно сообщается через Telegram.",
    services_ref=["erp", "automation", "telegram-bot"],
    case_ref=["tizimly"],
    faq=[("Можно ли автоматически связать остатки склада с продажами?","Да — в платформе Tizimly каждая продажа автоматически обновляет остатки склада."),
         ("Можно ли автоматически уведомлять клиента о статусе доставки?","Да, через Telegram-бота можно автоматически отправлять уведомления о статусе заказа (собран, отправлен, доставлен).")]),
  "en": dict(nav="Logistics", h1="Solutions for Logistics & Warehousing",
    title="Logistics and Warehouse Automation Solutions | promtchi",
    meta="Automating logistics and warehouse processes: real-time stock control, order tracking, Telegram notifications.",
    intro="We digitize warehouse and delivery processes so stock levels, orders and delivery status can be tracked in real time.",
    challenges=["Warehouse stock is counted manually and often has errors", "Order status (picking → shipping → delivery) isn't tracked", "Delivery planning across different addresses is done manually", "Warehouse and sales systems aren't connected"],
    approach="We connect an ERP inventory module to your CRM/sales system — every operation (inbound, outbound, shipping) automatically updates stock, with status reported instantly via Telegram.",
    services_ref=["erp", "automation", "telegram-bot"],
    case_ref=["tizimly"],
    faq=[("Can warehouse stock be automatically linked to sales?","Yes — on our Tizimly platform, every sale automatically updates warehouse stock."),
         ("Can customers be automatically notified about delivery status?","Yes, a Telegram bot can automatically send updates on order status (picked, shipped, delivered).")]),
},
"ishlab-chiqarish": {
  "uz": dict(nav="Ishlab chiqarish", h1="Ishlab chiqarish uchun yechimlar",
    title="Ishlab chiqarish uchun ERP va boshqaruv tizimlari | promtchi",
    meta="Ishlab chiqarish korxonalari uchun ERP: xom ashyo, xodimlar, moliya va KPI'ni bitta dashboard'da boshqaring.",
    intro="Ishlab chiqarish jarayonlarini — xom ashyo hisobi, xodimlar samaradorligi, moliya va hisobotni — bitta markazlashgan tizimga birlashtiramiz.",
    challenges=["Xom ashyo va tayyor mahsulot hisobi qo'lda yuritiladi", "Xodimlar samaradorligi (KPI) tizimli o'lchanmaydi", "Moliyaviy hisobot ishlab chiqarish ma'lumotlaridan alohida yuritiladi", "Boshqaruv real vaqtli ko'rinishga ega emas — qarorlar kechikadi"],
    approach="ERP tizimi orqali xom ashyo, ishlab chiqarish bosqichlari, xodimlar KPI'si va moliyani bitta ma'lumotlar bazasiga bog'lab, real vaqtli dashboard orqali nazorat qilish imkonini beramiz.",
    services_ref=["erp", "crm", "automation"],
    case_ref=["chindan-group"],
    faq=[("KPI va bonuslarni avtomatik hisoblash mumkinmi?","Ha — ERP tizimimizda KPI va bonuslar belgilangan formulalar asosida avtomatik hisoblanadi."),
         ("Moliya va ishlab chiqarish ma'lumotlarini bitta joyda ko'rish mumkinmi?","Ha, real vaqtli dashboard orqali tushum, xarajat va ishlab chiqarish ko'rsatkichlari bitta ekranda ko'rinadi.")]),
  "ru": dict(nav="Производство", h1="Решения для производства",
    title="ERP и системы управления для производства | promtchi",
    meta="ERP для производственных предприятий: сырьё, персонал, финансы и KPI в едином дашборде.",
    intro="Объединяем производственные процессы — учёт сырья, эффективность персонала, финансы и отчётность — в единой централизованной системе.",
    challenges=["Учёт сырья и готовой продукции ведётся вручную", "Эффективность персонала (KPI) не измеряется системно", "Финансовая отчётность ведётся отдельно от производственных данных", "У руководства нет представления в реальном времени — решения запаздывают"],
    approach="Через ERP-систему связываем сырьё, этапы производства, KPI персонала и финансы в единой базе данных с контролем через дашборд в реальном времени.",
    services_ref=["erp", "crm", "automation"],
    case_ref=["chindan-group"],
    faq=[("Можно ли автоматически рассчитывать KPI и бонусы?","Да — в нашей ERP-системе KPI и бонусы рассчитываются автоматически по заданным формулам."),
         ("Можно ли видеть финансовые и производственные данные в одном месте?","Да, дашборд в реальном времени показывает доходы, расходы и производственные показатели на одном экране.")]),
  "en": dict(nav="Manufacturing", h1="Solutions for Manufacturing",
    title="ERP and Management Systems for Manufacturing | promtchi",
    meta="ERP for manufacturing companies: raw materials, staff, finance and KPIs in one real-time dashboard.",
    intro="We bring manufacturing processes — raw material tracking, staff performance, finance and reporting — into one centralized system.",
    challenges=["Raw material and finished-goods tracking is done manually", "Staff performance (KPI) isn't measured systematically", "Financial reporting is kept separate from production data", "Management lacks real-time visibility — decisions lag behind"],
    approach="Through an ERP system, we link raw materials, production stages, staff KPIs and finance into a single database with real-time dashboard oversight.",
    services_ref=["erp", "crm", "automation"],
    case_ref=["chindan-group"],
    faq=[("Can KPIs and bonuses be calculated automatically?","Yes — in our ERP systems, KPIs and bonuses are calculated automatically using defined formulas."),
         ("Can finance and production data be viewed in one place?","Yes, a real-time dashboard shows revenue, expenses and production metrics on a single screen.")]),
},
}
